### ISSUE TITLE
Timestamps not converted to Date anymore

### ISSUE THREAD

**Issue by kflip** [strongloop/strong-remoting#238] opened 2015-08-27 00:37 UTC
Timestamps passed as parameter to remote methods worked in older versions:
e.g.: 
	from=1440631417
or in milliseconds
	from=1440631417000

It fails to instantiate a new Date() due a missing conversion from String to Number.
I've made a workaround in Shared-Method.js, but you might want to solve this somewhere else (HttpContext) or differently.

thanks
	
	...
	function convertValueToTargetType
	...
	case 'date': {
		
		// could be a timestamp as string
		if (!isNaN(value) && typeof value == 'string') {
		    value = Number(value).valueOf();
 	    } 
	
		return new Date(value);
	}

**Comment by richardpringle** [comment] 2016-05-04 15:56
@bajtos, can you confirm if this is expected behavior or not?

If we don't expect a number to coerce, then I think there should be a warning in the docs.

**Comment by bajtos** [comment] 2016-05-09 09:09
Interesting. So if my understanding is correct, when we have `{ accepts: { arg: 'd', type: 'Date' } }`,
it used to be possible to send `?from=1440631417`, where the value was treated as timestamp. @kflip could you please confirm? Do you happen to know the last version where this was still working?

**Comment by bajtos** [comment] 2016-05-27 12:24
This is actually tricky. Both `new Date('0')` and `new Date(0)` are valid ways how to create a new Date instance, however each returns a different value. It makes sense to me to always convert timestamp-like values to numbers before creating a Date value.

I have a question though. How to handle numeric values in scientific notation (e.g. `?ts=1.234e%2B30`) and values that cannot be accurately represented as integer numbers (e.g. `?ts=2343546576878989879789`)? I am proposing to reject such values and return HTTP 400 Bad Request response to the client.

/cc @STRML

**Comment by richardpringle** [comment] 2016-09-16 17:42
@bajtos can this be closed now since #349 was landed?

**Comment by bajtos** [comment] 2016-09-19 11:13
Yes, I am closing this issue as fixed (in LoopBack 3.0).

**Closed by bajtos** 2016-09-19 11:13 UTC
Labels: #wip, bug
