### ISSUE TITLE
Compression middleware breaks `EventSource` requests

### ISSUE THREAD

**Issue by ritch** [strongloop/strong-remoting#234] opened 2015-08-06 20:43 UTC
I believe this is the cause of `:ERR_INCOMPLETE_CHUNKED_ENCODING` errors.

Upgrading the version of `event-stream` might fix this.

**Comment by fabien** [comment] 2015-11-10 09:49
Yes, this is the cause - a good workaround would be:

```
function compressFilter(req, res) {
    var accept = req.headers['accept'] || '';
    if (accept.indexOf('text/event-stream') > -1) return false;
    return compression.filter(req, res);
};

app.middleware('initial', compression({ filter: compressFilter }));
```

Hasn't this been fixed already? I haven't used your event-stream implementation, but I have been doing something similar and had the same issue.

**Comment by richardpringle** [comment] 2016-05-04 15:37
@0candy, did you have an issue concerning streams and compression?

**Comment by 0candy** [comment] 2016-05-04 15:58
@richardpringle This [https://github.com/strongloop/strong-remoting/pull/294] should fix the issue.

**Comment by richardpringle** [comment] 2016-05-04 18:27
@0candy thanks, closing.

**Closed by richardpringle** 2016-05-04 18:27 UTC
Labels: #tob
